CREATE TABLE UsersData (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(50) NOT NULL,
    email VARCHAR2(100)
);

CREATE TABLE LostItems (
    lost_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES Users(user_id),
    item_name VARCHAR2(50),
    location VARCHAR2(100),
    lost_date DATE,
    description VARCHAR2(200),
    contact_info VARCHAR2(100)
);

CREATE TABLE FoundItems (
    found_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES Users(user_id),
    item_name VARCHAR2(50),
    location VARCHAR2(100),
    found_date DATE,
    description VARCHAR2(200),
    contact_info VARCHAR2(100)
);

drop TABLE UsersData;
drop  TABLE LostItems;
drop table FoundItems;

-- Create UsersData table
CREATE TABLE UsersData (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(50) NOT NULL,
    email VARCHAR2(100)
);

-- Create LostItems table (FIXED - now references UsersData)
CREATE TABLE LostItems (
    lost_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES UsersData(user_id),
    item_name VARCHAR2(50),
    location VARCHAR2(100),
    lost_date DATE,
    description VARCHAR2(200),
    contact_info VARCHAR2(100)
);

-- Create FoundItems table (FIXED - now references UsersData)
CREATE TABLE FoundItems (
    found_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES UsersData(user_id),
    item_name VARCHAR2(50),
    location VARCHAR2(100),
    found_date DATE,
    description VARCHAR2(200),
    contact_info VARCHAR2(100)
);

-- Drop tables if they exist (to start fresh)
DROP TABLE FoundItems CASCADE CONSTRAINTS;
DROP TABLE LostItems CASCADE CONSTRAINTS;
DROP TABLE UsersData CASCADE CONSTRAINTS;

-- Create UsersData table
CREATE TABLE UsersData (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(50) NOT NULL,
    email VARCHAR2(100)
);

-- Create LostItems table
CREATE TABLE LostItems (
    lost_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES UsersData(user_id),
    item_name VARCHAR2(50),
    location VARCHAR2(100),
    lost_date DATE,
    description VARCHAR2(200),
    contact_info VARCHAR2(100)
);

-- Create FoundItems table
CREATE TABLE FoundItems (
    found_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES UsersData(user_id),
    item_name VARCHAR2(50),
    location VARCHAR2(100),
    found_date DATE,
    description VARCHAR2(200),
    contact_info VARCHAR2(100)
);

-- Commit the changes
COMMIT;
INSERT INTO UsersData (username, password, email) VALUES ('test', 'test123', 'test@example.com');
COMMIT;

SELECT * FROM UsersData;

DELETE FROM UsersData WHERE username = 'test';
COMMIT;

-- First, drop any existing tables (if they exist)
DROP TABLE FoundItems CASCADE CONSTRAINTS;
DROP TABLE LostItems CASCADE CONSTRAINTS;
DROP TABLE UsersData CASCADE CONSTRAINTS;

CREATE TABLE UsersData (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(50) NOT NULL,
    email VARCHAR2(100)
);

CREATE TABLE LostItems (
    lost_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES UsersData(user_id),
    item_name VARCHAR2(50),
    location VARCHAR2(100),
    lost_date DATE,
    description VARCHAR2(200),
    contact_info VARCHAR2(100)
);


CREATE TABLE FoundItems (
    found_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES UsersData(user_id),
    item_name VARCHAR2(50),
    location VARCHAR2(100),
    found_date DATE,
    description VARCHAR2(200),
    contact_info VARCHAR2(100)
);

COMMIT;

-- Drop all three tables
DROP TABLE FoundItems CASCADE CONSTRAINTS;
DROP TABLE LostItems CASCADE CONSTRAINTS;
DROP TABLE UsersData CASCADE CONSTRAINTS;

-- Create UsersData table
CREATE TABLE UsersData (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(50) NOT NULL,
    email VARCHAR2(100)
);

-- Verify UsersData was created
SELECT table_name FROM user_tables WHERE table_name = 'USERSDATA';


DROP TABLE FoundItems CASCADE CONSTRAINTS;
DROP TABLE LostItems CASCADE CONSTRAINTS;
DROP TABLE UsersData CASCADE CONSTRAINTS;

-- Create UsersData table
CREATE TABLE UsersData (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(50) NOT NULL,
    email VARCHAR2(100)
);

-- Create LostItems table
CREATE TABLE LostItems (
    lost_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES UsersData(user_id),
    item_name VARCHAR2(50),
    location VARCHAR2(100),
    lost_date DATE,
    description VARCHAR2(200),
    contact_info VARCHAR2(100)
);

-- Create FoundItems table
CREATE TABLE FoundItems (
    found_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES UsersData(user_id),
    item_name VARCHAR2(50),
    location VARCHAR2(100),
    found_date DATE,
    description VARCHAR2(200),
    contact_info VARCHAR2(100)
);

-- Commit the changes
COMMIT;

-- Verify tables were created
SELECT table_name FROM user_tables 
WHERE table_name IN ('USERSDATA', 'LOSTITEMS', 'FOUNDITEMS')
ORDER BY table_name;

SELECT USER FROM DUAL;

SELECT SYS_CONTEXT('USERENV', 'CON_NAME') FROM DUAL;

ALTER SESSION SET CONTAINER = FREEPDB1;

SELECT SYS_CONTEXT('USERENV', 'CON_NAME') FROM DUAL;

DROP TABLE FoundItems CASCADE CONSTRAINTS;
DROP TABLE LostItems CASCADE CONSTRAINTS;
DROP TABLE UsersData CASCADE CONSTRAINTS;

-- Create UsersData table
CREATE TABLE UsersData (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(50) NOT NULL,
    email VARCHAR2(100)
);

-- Create LostItems table
CREATE TABLE LostItems (
    lost_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES UsersData(user_id),
    item_name VARCHAR2(50),
    location VARCHAR2(100),
    lost_date DATE,
    description VARCHAR2(200),
    contact_info VARCHAR2(100)
); 

-- Create FoundItems table
CREATE TABLE FoundItems (
    found_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES UsersData(user_id),
    item_name VARCHAR2(50),
    location VARCHAR2(100),
    found_date DATE,
    description VARCHAR2(200),
    contact_info VARCHAR2(100)
);

COMMIT;
SELECT table_name FROM user_tables 
WHERE table_name IN ('USERSDATA', 'LOSTITEMS', 'FOUNDITEMS')
ORDER BY table_name;








-- Connect to FREEPDB1 first
ALTER SESSION SET CONTAINER = FREEPDB1;

-- Add status column to LostItems table
ALTER TABLE LostItems ADD status VARCHAR2(20) DEFAULT 'LOST';

-- Update existing records to have 'LOST' status
UPDATE LostItems SET status = 'LOST' WHERE status IS NULL;

COMMIT;

-- Verify the column was added
SELECT * FROM LostItems;

-- to add status column to LostItems table

-- Add status column (default is 'LOST')
ALTER TABLE LostItems ADD status VARCHAR2(20) DEFAULT 'LOST';

-- Update existing records to have 'LOST' status
UPDATE LostItems SET status = 'LOST' WHERE status IS NULL;

COMMIT;

-- Verify the column was added
SELECT * FROM LostItems;

-- You should now see a 'status' column with value 'LOST' for all items

-- Switch to FREEPDB1
ALTER SESSION SET CONTAINER = FREEPDB1;

-- Check if status column exists
DESC LostItems;


ALTER TABLE LostItems ADD status VARCHAR2(20) DEFAULT 'LOST';
UPDATE LostItems SET status = 'LOST' WHERE status IS NULL;
COMMIT;


SELECT lost_id, item_name, status, user_id FROM LostItems;



-- Replace '1' with an actual lost_id from your table
UPDATE LostItems SET status = 'FOUND' WHERE lost_id = 1;
COMMIT;

-- Check if it worked
SELECT lost_id, item_name, status FROM LostItems WHERE lost_id = 1;

SELECT * FROM LostItems WHERE lost_id = 1;



-- Run this in Oracle SQL Developer to verify and fix status column

-- 1. Switch to FREEPDB1
ALTER SESSION SET CONTAINER = FREEPDB1;

-- 2. Check current table structure
DESC LostItems;

-- 3. View all data with status
SELECT lost_id, item_name, status FROM LostItems;

-- 4. If status column exists but has NULL values, fix them
UPDATE LostItems SET status = 'LOST' WHERE status IS NULL;
COMMIT;


-- 6. Verify all items have status
SELECT 
    lost_id,
    item_name,
    CASE 
        WHEN status IS NULL THEN 'NULL (ERROR!)'
        ELSE status
    END as status_display,
    user_id
FROM LostItems
ORDER BY lost_id;

-- 7. Check if any NULL statuses remain
SELECT COUNT(*) as null_status_count 
FROM LostItems 
WHERE status IS NULL;

-- Should return 0. If not, run UPDATE again:
COMMIT;




-- Switch to FREEPDB1
ALTER SESSION SET CONTAINER = FREEPDB1;

-- Check if FoundItems table exists
DESC FoundItems;

-- Add status column to FoundItems (if it doesn't exist)
ALTER TABLE FoundItems ADD status VARCHAR2(20) DEFAULT 'AVAILABLE';

COMMIT;

-- Verify
SELECT * FROM FoundItems;